steps:
  # build the deploy container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "--file",
        "dockerfiles/server.dockerfile",
        "-t",
        "gcr.io/mlops-exam-project/server:latest",
        ".",
      ]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/mlops-exam-project/server:latest"]

  # deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "services"
      - "replace"
      - 'service-monitoring.yaml'
      - "--region"
      - "europe-west1"
      - "--platform"
      - "managed"
