steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build','--build-arg','KEY=$_WANDB_API_KEY','--file','dockerfiles/train_model.dockerfile','-t', 'gcr.io/mlops-exam-project/train_docker', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/mlops-exam-project/server']
