program: main.py
method: bayes
command:
  - python
  - -u
  - src/main.py
  - -c
  - config/main.yaml
  - fit
  - ${args}
metric:
  goal: minimize
  name: val_loss
parameters:
  model.lr:
    values: [0.1, 0.05, 0.01, 0.005, 0.001]
  data.batch_size:
    values: [32, 64, 128]
  trainer.max_epochs:
    values: [1, 2, 5, 10, 20]