name: testing

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        cache: "pip"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install dvc
        pip install dvc[gs]
        pip install gcloud

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GDRIVE_CREDENTIALS_DATA }}'

    - name: Cache DVC data
      uses: actions/cache@v2
      with:
        path: |
          .dvc
        key: dvc-${{ runner.os }}-${{ hashFiles('**/data.dvc') }}

    - name: Restore Cache
      uses: actions/cache@v2
      with:
        path: |
          .dvc
        key: dvc-${{ runner.os }}-${{ hashFiles('**/data.dvc') }}

    - name: Pull DVC data if cache is not restored
      run: |
        if [ -z "$GITHUB_RESTORE_CACHE" ]; then
          dvc pull
        fi

    - name: Run tests with coverage
      run: |
        pip install pytest pytest-cov
        pytest tests/

    - name: Generate Report
      run: |
        pytest --cov=src tests/

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
            CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    - name: Set status check
      run: echo "::set-output name=status::success"
